# Generated by Django 5.2.7 on 2025-10-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('ingredients', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('preparation_time', models.FloatField()),
            ],
        ),
    ]
